### ISSUE TITLE
figtree can't run (java error)

### ISSUE THREAD

**Issue by juancholkovich** [rambaut/figtree#119]
Hi.

I'm trying to run figtree but I have a problem and the next message is shown:

===============
javax.swing.UIManager$LookAndFeelInfo[Metal javax.swing.plaf.metal.MetalLookAndFeel]
javax.swing.UIManager$LookAndFeelInfo[Nimbus javax.swing.plaf.nimbus.NimbusLookAndFeel]
javax.swing.UIManager$LookAndFeelInfo[CDE/Motif com.sun.java.swing.plaf.motif.MotifLookAndFeel]
javax.swing.UIManager$LookAndFeelInfo[Mac OS X com.apple.laf.AquaLookAndFeel]
Exception in thread "main" java.lang.NoClassDefFoundError: com/apple/eawt/AboutHandler
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1007)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:801)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:699)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:622)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:580)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:292)
	at jam.mac.Utils.macOSXRegistration(Unknown Source)
	at jam.framework.MultiDocApplication.initialize(Unknown Source)
	at figtree.application.FigTreeApplication.main(Unknown Source)
Caused by: java.lang.ClassNotFoundException: com.apple.eawt.AboutHandler
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
	... 14 more
=======================
I have not able to found a solution in any blog (regarding with figtree or java). How can I fix this problem?

Regards, 

Juan.

**Comment by NeuKon** [comment]
Looks similar to what I encountered on a Windows PC
[ #105 figtree does not start on windows](https://github.com/rambaut/figtree/issues/105)

What machine and java version are you using? I did not manage to get passed this so eventually had to use another software package for my purposes.

**Comment by rambaut** [comment]
Are you using Java 9? At the moment, FigTree is not compatible with Java 9 although I am working to fix this. The solution is to install Java 8.

Andrew

**Comment by dinhe878** [comment]
Hi, I can not launch Figtree v1.4.3 on Mac (OS 10.13.2 High Sierra) with java 1.8.0_144-b01.

**Comment by rambaut** [comment]
Please try the v1.4.4 pre-release:

https://github.com/rambaut/figtree/releases/tag/v1.4.4pre20171111 <https://github.com/rambaut/figtree/releases/tag/v1.4.4pre20171111>

I believe this is still not compatible with Java 1.9 on the Mac so do not upgrade from Java 1.8.

Andrew

**Comment by dinhe878** [comment]
Thanks it’s working now.

best,
Ding

**Comment by cicindel** [comment]
Just wanted to report that v1.4.4 pre-release fixed the issue present in stable v1.4.3 (from Ubuntu repos; Ubuntu 18.04 64bit, openjdk version "1.8.0_181").

Do you have any plans distributing your software through platform-agnistic package managers like conda (e.g. submit it to [Bioconda channel](https://bioconda.github.io/))? It used to be a python package manager but nowadays you can install almost any scientific software, including even Beast.

Thanks for consideration.

**Comment by rambaut** [comment]
I don't have any immediate plans to submit it to bioconda due to severe limits on my time at present. I would happy for anyone else to do so.
