### ISSUE TITLE
Problems exporting big file to PDF

### ISSUE THREAD

**Issue by tapeda** [rambaut/figtree#120]
Here what I have in the console:
bash-3.2$ java -jar /Users/David/Desktop/FigTree_v1.4.3/lib/figtree.jar 
javax.swing.UIManager$LookAndFeelInfo[Metal javax.swing.plaf.metal.MetalLookAndFeel]
javax.swing.UIManager$LookAndFeelInfo[Nimbus com.sun.java.swing.plaf.nimbus.NimbusLookAndFeel]
javax.swing.UIManager$LookAndFeelInfo[CDE/Motif com.sun.java.swing.plaf.motif.MotifLookAndFeel]
javax.swing.UIManager$LookAndFeelInfo[Mac OS X com.apple.laf.AquaLookAndFeel]
objc[14294]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fff8c19eb68) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x11bf85cd8). One of the two will be used. Which one is undefined.
Exception in thread "AWT-EventQueue-0" java.lang.UnsupportedOperationException
	at java.util.AbstractList.add(AbstractList.java:131)
	at java.util.AbstractList.add(AbstractList.java:91)
	at figtree.treeviewer.decorators.DiscreteColourDecorator.setAttributes(Unknown Source)
	at figtree.treeviewer.AttributeColourController.getDecoratorForAttribute(Unknown Source)
	at figtree.treeviewer.AttributeColourController.setSettings(Unknown Source)
	at jam.controlpalettes.BasicControlPalette.setSettings(Unknown Source)
	at figtree.application.FigTreeFrame.readData(Unknown Source)
	at figtree.application.FigTreeFrame.readFromFile(Unknown Source)
	at jam.framework.DocumentFrame.openFile(Unknown Source)
	at figtree.application.FigTreeApplication.doOpenFile(Unknown Source)
	at jam.framework.Application.doOpen(Unknown Source)
	at jam.framework.Application$4.actionPerformed(Unknown Source)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2028)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2351)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:387)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:242)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:389)
	at com.apple.laf.ScreenMenuItem.actionPerformed(ScreenMenuItem.java:95)
	at java.awt.MenuItem.processActionEvent(MenuItem.java:650)
	at java.awt.MenuItem.processEvent(MenuItem.java:609)
	at java.awt.MenuComponent.dispatchEventImpl(MenuComponent.java:343)
	at java.awt.MenuComponent.dispatchEvent(MenuComponent.java:331)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:720)
	at java.awt.EventQueue.access$400(EventQueue.java:82)
	at java.awt.EventQueue$2.run(EventQueue.java:676)
	at java.awt.EventQueue$2.run(EventQueue.java:674)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:690)
	at java.awt.EventQueue$3.run(EventQueue.java:688)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:687)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at figtree.treeviewer.TreePane.calibrate(Unknown Source)
	at figtree.treeviewer.TreePane.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(JComponent.java:870)
	at javax.swing.JComponent.paint(JComponent.java:1046)
	at javax.swing.JViewport.paint(JViewport.java:795)
	at javax.swing.JComponent.paintChildren(JComponent.java:870)
	at javax.swing.JComponent.paint(JComponent.java:1046)
	at javax.swing.JComponent._paintImmediately(JComponent.java:5106)
	at javax.swing.JComponent.paintImmediately(JComponent.java:4890)
	at javax.swing.RepaintManager$3.run(RepaintManager.java:814)
	at javax.swing.RepaintManager$3.run(RepaintManager.java:802)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:802)
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:745)
	at javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:725)
	at javax.swing.RepaintManager.access$1000(RepaintManager.java:46)
	at javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1680)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:715)
	at java.awt.EventQueue.access$400(EventQueue.java:82)
	at java.awt.EventQueue$2.run(EventQueue.java:676)
	at java.awt.EventQueue$2.run(EventQueue.java:674)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:685)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at figtree.treeviewer.TreePane.calibrate(Unknown Source)
	at figtree.treeviewer.TreePane.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(JComponent.java:870)
	at javax.swing.JComponent.paint(JComponent.java:1046)
	at javax.swing.JViewport.paint(JViewport.java:795)
	at javax.swing.JComponent._paintImmediately(JComponent.java:5106)
	at javax.swing.JComponent.paintImmediately(JComponent.java:4890)
	at javax.swing.RepaintManager$3.run(RepaintManager.java:814)
	at javax.swing.RepaintManager$3.run(RepaintManager.java:802)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:802)
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:745)
	at javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:725)
	at javax.swing.RepaintManager.access$1000(RepaintManager.java:46)
	at javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1680)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:715)
	at java.awt.EventQueue.access$400(EventQueue.java:82)
	at java.awt.EventQueue$2.run(EventQueue.java:676)
	at java.awt.EventQueue$2.run(EventQueue.java:674)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:685)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
2017-12-12 15:08:29.030 java[14294:418487] Persistent UI failed to open file file://localhost/Users/David/Library/Saved%20Application%20State/com.apple.javajdk16.cmd.savedState/window_1.data: Permission denied (13)

Thanks friend!

**Comment by rambaut** [comment]
What OS is this on?

A.

**Comment by tapeda** [comment]
Mac OS  High Sierra 10.13.2, If you want I can send you privately the file which is reporting me this problems…I cannot also see the name of my taxa. Thanks!

**Comment by rambaut** [comment]
In which case could you download and try the v1.4.4 pre-release:

https://github.com/rambaut/figtree/releases/tag/v1.4.4pre20171111 <https://github.com/rambaut/figtree/releases/tag/v1.4.4pre20171111>

I believe this is still not compatible with Java 1.9 on the Mac so do not upgrade from Java 1.8.

If there is still an issue, let me know.

Andrew

**Comment by tapeda** [comment]
Ok, I just download and tried, and I doesn’t work.

The tip labels also don’t appear, if you uncheck the option the screen shows the tree. Let me share with you the file, we are trying to extract the figure in PDF for our paper. I think that maybe there are too many number of taxa? Thanks for everythin, I would appreciate a lot your fast answer and your help. Thanks! Regards from Spain.

David

**Comment by rambaut** [comment]
Can you post the file here - or email it to me.

**Comment by tapeda** [comment]
Dear Andrew,

First of all my best wishes in the New Year 2018. I would like to know if you receive at the end my tree file in which I experimented problems during PDF export. Your software is being very useful to us in other to analyze and plot your results. We are very interested in obtain this plot because we are enrolled on the writing of a paper related with this data, It takes me a lot of time to group, contract and paint the different groups of data and I would like to show the results in the paper. 

Thank you very much.

Sincerely yours 

David

**Comment by tapeda** [comment]
Dear Andrew,

I am still having problems with PDF export and my huge tree, even with the last version 1.4.4. In the last version I can't open the tree (it opens but I doesn't appear the image in the screen) and also is not able to export. Thanks!

**Comment by yzongzjnu** [comment]
I have the same problem. If there are additional information in the tree file, figtree cannot not export the figure to pdf. However, if the tree file was exported to a nexus format and re-open in Figtree, it can export PDF file. I think the additional information blocked the PDF export. Unfortunately, the additional information is the key point I need.

**Comment by tapeda** [comment]
That’s the point...the additional information is the key point I need too...

Enviado desde mi iPad

**Comment by KubraTeksen** [comment]
How did you solve this problem? I couldnt export as pdf. 
Thanks..

**Comment by theo-llewellyn** [comment]
If its any help the following allowed me to save to pdf with annotations when I had the same problem:

1. open the tree in figtree and show annotations
2. export tree to a new nexus, making sure to tick the 'save as currently displayed', 'include figtree block', 'include annotations' options
3. open the new nexus
4. export to pdf
