### ISSUE TITLE
Messy output on Ubuntu 18.04

### ISSUE THREAD

**Issue by Dmole** [rambaut/figtree#137]
```
> java -jar /opt/figtree.jar 
javax.swing.UIManager$LookAndFeelInfo[Metal javax.swing.plaf.metal.MetalLookAndFeel]
javax.swing.UIManager$LookAndFeelInfo[Nimbus javax.swing.plaf.nimbus.NimbusLookAndFeel]
javax.swing.UIManager$LookAndFeelInfo[CDE/Motif com.sun.java.swing.plaf.motif.MotifLookAndFeel]
javax.swing.UIManager$LookAndFeelInfo[GTK+ com.sun.java.swing.plaf.gtk.GTKLookAndFeel]
Gtk-Message: 15:10:53.483: Failed to load module "canberra-gtk-module"
Exception while loading the ApplicationAdapter:
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at jam.mac.Utils.registerDesktopApplication(Unknown Source)
	at jam.framework.MultiDocApplication.initialize(Unknown Source)
	at figtree.application.FigTreeApplication.main(Unknown Source)
Caused by: java.lang.UnsupportedOperationException: The APP_ABOUT action is not supported on the current platform!
	at java.desktop/java.awt.Desktop.checkActionSupport(Desktop.java:380)
	at java.desktop/java.awt.Desktop.setAboutHandler(Desktop.java:696)
	at jam.java9only.ApplicationAdapter.registerApplication(Unknown Source)
	... 7 more
```

**Comment by jvollme** [comment]
I have the same on Red Hat Enterprise Linux Server release 7.6 (Maipo). 
I am using openjdk 11.0.1.

Apart from those messy error-messages, figtree seems to be working correctly, though...
