### ISSUE TITLE
java exception 

### ISSUE THREAD

**Issue by BettyAC** [rambaut/figtree#176]
javax.swing.UIManager$LookAndFeelInfo[Metal javax.swing.plaf.metal.MetalLookAndFeel]
javax.swing.UIManager$LookAndFeelInfo[Nimbus javax.swing.plaf.nimbus.NimbusLookAndFeel]
javax.swing.UIManager$LookAndFeelInfo[CDE/Motif com.sun.java.swing.plaf.motif.MotifLookAndFeel]
javax.swing.UIManager$LookAndFeelInfo[GTK+ com.sun.java.swing.plaf.gtk.GTKLookAndFeel]
Exception in thread "main" java.awt.HeadlessException:
No X11 DISPLAY variable was set, but this program performed an operation which requires it.
        at java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:204)
        at java.awt.Window.<init>(Window.java:536)
        at java.awt.Frame.<init>(Frame.java:420)
        at java.awt.Frame.<init>(Frame.java:385)
        at javax.swing.JFrame.<init>(JFrame.java:189)
        at jam.framework.AbstractFrame.<init>(Unknown Source)
        at jam.framework.DocumentFrame.<init>(Unknown Source)
        at figtree.application.FigTreeFrame.<init>(Unknown Source)
        at figtree.application.FigTreeApplication$3.createDocumentFrame(Unknown Source)
        at jam.framework.MultiDocApplication.createDocumentFrame(Unknown Source)
        at jam.framework.MultiDocApplication.doOpenFile(Unknown Source)
        at figtree.application.FigTreeApplication.doOpenFile(Unknown Source)
        at jam.framework.Application.doOpen(Unknown Source)
        at figtree.application.FigTreeApplication.main(Unknown Source)

**Comment by Oliver-Lorenz-dev** [comment]
You need to enable X11 forwarding here. If you are connecting to a HPC cluster, you can connect via "ssh -X" to enable X11 forwarding.
