### ISSUE TITLE
Problem rendering trees with node labels (with non-alphanumerics?)

### ISSUE THREAD

**Issue by GoogleCodeExporter** [rambaut/figtree#56]
```
What steps will reproduce the problem?
1. Load the attached tree file.
2.
3.

What is the expected output? What do you see instead?

The tree should appear in the FigTree viewer. Instead, the program asks what 
the user node labels should be called (as it should) and then nothing further 
happens.

What version of the product are you using? On what operating system?

Version 1.4.0 on Mac OS 10.8.2.

Please provide any additional information below.

Removing all the < signs and the label n/a in the tree description will cause 
the file to load properly; removing only one class or the other will not. At 
first, I though it was a general problem with having non-alphanumerics in the 
node labels; however, other similar (but smaller) test trees made by hand work 
fine. Only larger trees like this seem to fail.
```

Original issue reported on code.google.com by `olaf.bininda@uni-oldenburg.de` on 12 Feb 2013 at 7:57

Attachments:
- [bootNodeTrees.tre](https://storage.googleapis.com/google-code-attachments/figtree/issue-56/comment-0/bootNodeTrees.tre)

**Comment by rambaut** [comment]
The issue is the bootstrap values are not strictly numerical (includes 'n/a' and '<1' etc. May need to allow alphanumerical labels.

It is throwing an exception - 
Exception in thread "AWT-EventQueue-0" java.lang.ClassCastException: java.lang.Double cannot be cast to java.lang.String
	at java.lang.String.compareTo(String.java:111)
	at java.util.TreeMap.put(TreeMap.java:568)
	at java.util.TreeSet.add(TreeSet.java:255)
	at figtree.treeviewer.decorators.DiscreteColourDecorator.setAttributes(DiscreteColourDecorator.java:107)
	at figtree.treeviewer.decorators.ColourDecorator.<init>(ColourDecorator.java:54)
	at figtree.treeviewer.decorators.DiscreteColourDecorator.<init>(DiscreteColourDecorator.java:88)
	at figtree.treeviewer.decorators.HSBDiscreteColourDecorator.<init>(HSBDiscreteColourDecorator.java:61)
	at figtree.treeviewer.AttributeColourController.getDecoratorForAttribute(AttributeColourController.java:171)
	at figtree.treeviewer.AttributeColourController.getColourDecorator(AttributeColourController.java:142)
	at figtree.treeviewer.painters.LegendPainterController$1.attributeComboChanged(LegendPainterController.java:106)
	at figtree.treeviewer.painters.AttributeComboHelper.fireAttributeSelectionChanged(AttributeComboHelper.java:293)
	at figtree.treeviewer.painters.AttributeComboHelper.access$200(AttributeComboHelper.java:46)
	at figtree.treeviewer.painters.AttributeComboHelper$2.actionPerformed(AttributeComboHelper.java:141)
