### ISSUE TITLE
Reading a file with a mix of integer and real node labels causes exception.

### ISSUE THREAD

**Issue by IngvarJackal** [rambaut/figtree#92]
FigTree stops spawning new windows after opening the file.

    $ uname -a
    Linux ingvar-Aspire-V5-552G 3.13.0-40-generic #69-Ubuntu SMP Thu Nov 13 17:53:56 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
    $ java -version
    java version "1.7.0_76"
    Java(TM) SE Runtime Environment (build 1.7.0_76-b13)
    Java HotSpot(TM) 64-Bit Server VM (build 24.76-b04, mixed mode)

    $ java -jar figtree.jar -help

                     FigTree v1.4.2, 2006-2014
                      Tree Figure Drawing Tool
                           Andrew Rambaut
    etc.

    $ java -jar figtree.jar
    javax.swing.UIManager$LookAndFeelInfo[Metal javax.swing.plaf.metal.MetalLookAndFeel]
    javax.swing.UIManager$LookAndFeelInfo[Nimbus javax.swing.plaf.nimbus.NimbusLookAndFeel]
    javax.swing.UIManager$LookAndFeelInfo[CDE/Motif com.sun.java.swing.plaf.motif.MotifLookAndFeel]
    javax.swing.UIManager$LookAndFeelInfo[GTK+ com.sun.java.swing.plaf.gtk.GTKLookAndFeel]

*here click in appeared GUI File -> Open -> MetaPiga-gblocks-gradient-stochastic-HKY85.tre -> Open*

    Exception in thread "AWT-EventQueue-0" java.lang.ClassCastException: java.lang.Double cannot be cast to java.lang.Integer
        at java.lang.Integer.compareTo(Integer.java:52)
        at java.util.TreeMap.put(TreeMap.java:560)
        at java.util.TreeSet.add(TreeSet.java:255)
        at figtree.treeviewer.decorators.ContinuousScale.setAttributes(Unknown Source)
        at figtree.treeviewer.AttributeColourController.getDecoratorForAttribute(Unknown Source)
        at figtree.treeviewer.AttributeColourController.getColourDecorator(Unknown Source)
        at figtree.treeviewer.painters.LegendPainterController$1.attributeComboChanged(Unknown Source)
        at figtree.treeviewer.painters.AttributeComboHelper.fireAttributeSelectionChanged(Unknown Source)
        at figtree.treeviewer.painters.AttributeComboHelper.access$200(Unknown Source)
        at figtree.treeviewer.painters.AttributeComboHelper$2.actionPerformed(Unknown Source)
        at javax.swing.JComboBox.fireActionEvent(JComboBox.java:1260)
        at javax.swing.JComboBox.setSelectedItem(JComboBox.java:588)
        at figtree.treeviewer.painters.AttributeComboHelper$1.treeChanged(Unknown Source)
        at figtree.treeviewer.DefaultTreeViewer.fireTreeChanged(Unknown Source)
        at figtree.treeviewer.DefaultTreeViewer.showTree(Unknown Source)
        at figtree.treeviewer.ExtendedTreeViewer.showTree(Unknown Source)
        at figtree.treeviewer.DefaultTreeViewer.setTrees(Unknown Source)
        at figtree.application.FigTreeFrame.readData(Unknown Source)
        at figtree.application.FigTreeFrame.readFromFile(Unknown Source)
        at jam.framework.DocumentFrame.openFile(Unknown Source)
        at figtree.application.FigTreeApplication.doOpenFile(Unknown Source)
        at jam.framework.Application.doOpen(Unknown Source)
        at jam.framework.Application$4.actionPerformed(Unknown Source)
        at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2018)
        at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2341)
        at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
        at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
        at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
        at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:833)
        at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:877)
        at java.awt.Component.processMouseEvent(Component.java:6516)
        at javax.swing.JComponent.processMouseEvent(JComponent.java:3321)
        at java.awt.Component.processEvent(Component.java:6281)
        at java.awt.Container.processEvent(Container.java:2229)
        at java.awt.Component.dispatchEventImpl(Component.java:4872)
        at java.awt.Container.dispatchEventImpl(Container.java:2287)
        at java.awt.Component.dispatchEvent(Component.java:4698)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4832)
        at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4492)
        at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4422)
        at java.awt.Container.dispatchEventImpl(Container.java:2273)
        at java.awt.Window.dispatchEventImpl(Window.java:2719)
        at java.awt.Component.dispatchEvent(Component.java:4698)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:740)
        at java.awt.EventQueue.access$300(EventQueue.java:103)
        at java.awt.EventQueue$3.run(EventQueue.java:699)
        at java.awt.EventQueue$3.run(EventQueue.java:697)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:87)
        at java.awt.EventQueue$4.run(EventQueue.java:713)
        at java.awt.EventQueue$4.run(EventQueue.java:711)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:710)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)

The file:

    $ file MetaPiga-gblocks-gradient-stochastic-HKY85.tre 
    MetaPiga-gblocks-gradient-stochastic-HKY85.tre: ASCII text, with very long lines
    $ cat MetaPiga-gblocks-gradient-stochastic-HKY85.tre 
    #NEXUS

    Begin trees;  [Treefile saved Sun Mar 29 23:02:26 EEST 2015]
    TREE 'Consensus_tree_110_replicates [MRE: 3.01%]' = [&R] [&C] (((((((AUTE01000013.1:0.20948218101451369,AYTU01000005.1:0.11144356575131122)0.75:0.08075315050334704,NZ_AVAI01000131.1:0.0995428633196639)0.79:1.1648262015885358,(HQ651181.2:0.0017192071604988837,X94434.2:0.0050626003326427645)0.92:3.2762251568658953E-4)0.35:2.3164971129671722E-4,CP002222.1:0.004560427223507678)0.12:1.0000000000000003E-4,(NC_004567.2:1.8144561884870996E-4,JQ933106.1:0.00128652219547667)0.24:1.0E-4)0.2:1.2850034442134573E-4,NZ_AGRI01000003.1:0.005333765062939651)0.68:0.002020803888196405,((((((NZ_CP005942.1:0.0029901076708879304,APHP01000077.1:0.0039924855759293065)1:0.002523145919087891,GU138150.2:0.005256363582551513)0.71:0.0019648807983296867,JQ900765.1:0.0448240674972887)0.54:0.0014242149489371103,NC_020229.1:0.008055869105099077)0.47:0.0010070120473729682,GU584090.1:0.011162022793904993)0.61:9.382883987592433E-4,CP001617.1:0.005145429076851266)0.34:0.0017105816617737635,((NZ_JIBX01000004.1:0.10462699203867461,JQ900767.1:0.004271864977941256)0.72:0.002724319413479967,FJ809773.1:0.005824391957555754)0.66:0.003557223519807219);
    End;

**Comment by IngvarJackal** [comment]
Export to SVG doesn't working too after opening the file (but it renders):

    Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
        at figtree.application.FigTreeFrame.doExportGraphic(Unknown Source)
        at figtree.application.FigTreeFrame$26.actionPerformed(Unknown Source)
        at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2018)
        at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2341)
        at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
        at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
        at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
        at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:833)
        at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:877)
        at java.awt.Component.processMouseEvent(Component.java:6516)
        at javax.swing.JComponent.processMouseEvent(JComponent.java:3321)
        at java.awt.Component.processEvent(Component.java:6281)
        at java.awt.Container.processEvent(Container.java:2229)
        at java.awt.Component.dispatchEventImpl(Component.java:4872)
        at java.awt.Container.dispatchEventImpl(Container.java:2287)
        at java.awt.Component.dispatchEvent(Component.java:4698)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4832)
        at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4492)
        at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4422)
        at java.awt.Container.dispatchEventImpl(Container.java:2273)
        at java.awt.Window.dispatchEventImpl(Window.java:2719)
        at java.awt.Component.dispatchEvent(Component.java:4698)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:740)
        at java.awt.EventQueue.access$300(EventQueue.java:103)
        at java.awt.EventQueue$3.run(EventQueue.java:699)
        at java.awt.EventQueue$3.run(EventQueue.java:697)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:87)
        at java.awt.EventQueue$4.run(EventQueue.java:713)
        at java.awt.EventQueue$4.run(EventQueue.java:711)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:710)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)

**Comment by IngvarJackal** [comment]
The file is a result from MetaPIGA.

**Comment by rambaut** [comment]
I have taken a look at this tree. The issue is the taxon names have  '.1'  at the end and this is being picked up as a numerical field (i.e., a bootstrap value). Changing these to '_1' seems to circumvent the issue. This is a bug in the parser.
